language: generic
sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.29.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - bin/reset-dev-container.sh
  - bin/test-backend.sh

# script:
#   - docker-compose build 
#   - docker-compose run -e TESTING=1 backend pytest -vv
#   - docker-compose run frontend npm run test:unit