version: "3.9"

services:
    db:
        container_name: ace2-gui-db
        build:
            context: .
            dockerfile: ./db/Dockerfile
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    backend:
        depends_on:
            - db
        container_name: ace2-gui-backend
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        environment:
            # The DATABASE_URL environment variable needs to be in the form of:
            # postgresql://<user>:<password>@db:5432/<database>
            - DATABASE_URL=${DATABASE_URL}
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /start.sh'

    frontend:
        # There is no depends_on for the frontend container since it should be able to be tested
        # fully independent of the backend API. Any API calls it makes should be mocked when testing since
        # the API calls themselves are already tested within the backend.
        container_name: ace2-gui-frontend
        build:
            context: .
            dockerfile: ./frontend/Dockerfile.dev
        environment:
            - CHOKIDAR_USEPOLLING=true
