version: "3.9"

services:
    db:
        container_name: ace2-gui-db
        build:
            context: .
            dockerfile: ./db/Dockerfile
        # volumes:
        #     - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    backend:
        depends_on:
            - db
        container_name: ace2-gui-backend
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        # volumes:
        #     - "./backend/app:/app"
        environment:
            - DATABASE_URL=${DATABASE_URL}
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /start.sh'

    frontend:
        container_name: ace2-gui-frontend
        build:
            context: .
            dockerfile: ./frontend/Dockerfile.dev
        # volumes:
        #     - "./frontend/app:/app"
        #     - "/app/node_modules"
        environment:
            - CHOKIDAR_USEPOLLING=true

# volumes:
#     postgres_data: