name: Build and Test

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  backend:
    name: Backend Tests  
    runs-on: ubuntu-latest
    
    env:
      POSTGRES_DB: ace
      POSTGRES_USER: ace
      POSTGRES_PASSWORD: supersecret
      DATABASE_URL: postgresql://ace:supersecret@db:5432/ace

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        run: docker-compose build backend
          
      - name: Test
        run: docker-compose run -e TESTING=1 backend pytest -vv

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        run: docker-compose build frontend
          
      - name: Lint
        run: docker-compose run frontend npm run lint
        
      - name: Unit tests
        run: docker-compose run frontend npm run test:unit
        
#       - name: End to end tests
#         run: docker-compose run frontend npm run test:e2e
